---
- hosts: all
  connection: local
  name: Get Installed Firmware Inventory
  gather_facts: False

  tasks:
  - name: Get Installed Firmware Inventory
    dellemc_get_firmware_inventory:
       idrac_ip:        "{{ idrac_ip }}"
       idrac_user:      "{{ idrac_user }}"
       idrac_pwd:       "{{ idrac_pwd }}"
